### ISSUE TITLE
从github获取图片文件时出错

### ISSUE THREAD

**Issue by LI-Mingyu** [Photenix-AI/plugins#5]
错误日志如下：
```
[2024-04-06 12:49:15,731] ERROR in app: Exception on /file_content [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "gh_interacter.py", line 15, in decorated_function
    return view_function(*args, **kwargs)
  File "gh_interacter.py", line 99, in get_file_content
    file_content_decoded = base64.b64decode(file_content_encoded).decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
172.17.0.1 - - [06/Apr/2024 12:49:15] "GET /file_content?repo_full_name=LI-Mingyu/DevAgents&file_path=cb2ef96b-62ea-42a1-a2ed-caf9b6db4f8d.png&branch_name= HTTP/1.0" 500 -
```

**Comment by DevBuddyConnor** [comment]
根据您提供的错误日志和问题描述，问题出现在尝试从GitHub获取图片文件并将其解码为UTF-8字符串时。具体来说，出现了一个 `UnicodeDecodeError`，这表明尝试将无法编码为UTF-8的字节序列进行解码。图片文件（如PNG）通常是二进制文件，而不是基于文本的文件，因此不能直接解码为UTF-8字符串。

### 解决方案
为了解决这个问题，我们需要在 `gh_interacter.py` 文件中的 `get_file_content` 函数中修改对文件内容的处理逻辑。具体的解决策略如下：

- 检查请求的文件路径，判断是否为图片或其他二进制文件。
- 对于图片或二进制文件，直接返回二进制内容，不尝试将其解码为UTF-8字符串。
- 对于文本文件，保持原有逻辑，尝试解码为UTF-8。

### 修改后的代码

```python
from flask import Flask, request, jsonify, send_file
import base64
import io
import os

app = Flask(__name__)

@app.route('/file_content')
def get_file_content():
    repo_full_name = request.args.get('repo_full_name')
    file_path = request.args.get('file_path')
    branch_name = request.args.get('branch_name', default='main')
    
    # 示例中省略了实际获取GitHub文件内容的逻辑
    # file_content_encoded = ...

    # 检查文件路径，确定是否以二进制文件扩展名结束
    if file_path.endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp')):
        # 以二进制形式处理文件内容
        file_content = base64.b64decode(file_content_encoded)
        return send_file(io.BytesIO(file_content), attachment_filename=os.path.basename(file_path))
    else:
        # 处理文本文件
        try:
            file_content_decoded = base64.b64decode(file_content_encoded).decode('utf-8')
            return file_content_decoded
        except UnicodeDecodeError:
            return jsonify({'error': 'File cannot be decoded as UTF-8'}), 500

if __name__ == '__main__':
    app.run()
```

修改后的代码引入了一种判断文件是否为二进制文件（如图片）的逻辑，并采取了相应的处理方式。这样的修改可以帮助避免在处理图片或其他二进制文件时遇到的 `UnicodeDecodeError`。

希望这个解决方案对您有帮助！

**[注意]** 该Comment由AI生成，仅供参考。

**Comment by ClawDevin** [comment]
根据Issue的描述和之后的讨论，这里提出一种修复方案来解决从GitHub获取图片文件时出现的错误。

**修改思路**：
问题的根源在于尝试将图片（二进制文件）的内容按UTF-8文本格式解码。我的解决方案是，通过`mimetypes`库先判断文件类型，如果是二进制文件（如图片），则不进行解码，而是直接返回一条信息说明当前无法处理二进制文件。这样既避免了解码错误，也对客户端提供了清晰的信息。

**修改后的代码**：
```python
@app.route('/file_content', methods=['GET'])
@require_api_key
def get_file_content():
    repo_full_name = request.args.get('repo_full_name')
    file_path = request.args.get('file_path')
    branch_name = request.args.get('branch_name')
    if not branch_name:
        # 检查是否存在 main 或 master 分支
        if check_branch_exists(repo_full_name, "main"):
            branch_name = "main"
        elif check_branch_exists(repo_full_name, "master"):
            branch_name = "master"
        else:
            return jsonify({'code': 404, 'message': 'No main or master branch found'}), 404

    if not repo_full_name or not file_path:
        return jsonify({'code': 400, 'message': 'Missing repo_full_name or file_path'}), 400

    github_api_url = f"https://api.github.com/repos/{repo_full_name}/contents/{file_path}?ref={branch_name}"
    headers = {'Authorization': f'token {os.environ.get("GITHUB_TOKEN")}'}
    response = requests.get(github_api_url, headers=headers)

    if response.status_code != 200:
        return jsonify({'code': response.status_code, 'message': f'Failed to fetch file content from {branch_name} branch'}), response.status_code

    file_content_encoded = response.json().get('content')
    if file_content_encoded is None:
        return jsonify({'code': 500, 'message': 'No content found in the response'}), 500

    # 使用mimetypes来判断文件类型
    file_mime_type, _ = mimetypes.guess_type(file_path)

    if file_mime_type and file_mime_type.startsWith('image'):
        return jsonify({'content': f'{file_path} 这是一个 {file_mime_type} 类型的二进制文件，当前无法处理。'})
    else:
        try:
            file_content_decoded = base64.b64decode(file_content_encoded).decode('utf-8')
            return jsonify({'content': file_content_decoded})
        except UnicodeDecodeError as e:
            return jsonify({'error': '文件解码错误，无法以utf-8格式解码'}), 500
```

**修改细节说明**：
- 使用`mimetypes.guess_type(file_path)`来确定文件的MIME类型。
- 如果文件为图片（或任何以`image`开头的类型），不尝试解码内容，而是直接返回一条消息，说明无法处理二进制文件。
- 对于非图片文件，如果存在解码错误，则返回相应错误信息。

这样的修改确保了，对于二进制文件，服务会显示一个友好的信息而不是尝试进行不适当的操作。这个方法既节省了资源，也提高了用户体验，通过清晰的消息告知用户当前的限制。

**[注意]** 该Comment由AI生成，仅供参考。
